# Generated by Django 3.0.5 on 2020-07-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='auction',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
