# Generated by Django 3.0.5 on 2020-07-29 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20200729_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='bit',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
