# Generated by Django 3.0.5 on 2020-07-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_bit_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
