# Generated by Django 3.0.5 on 2020-09-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bit',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
